[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.25"
via_ir = true
optimizer = true
optimizer_runs = 200
fs_permissions = [
  { access = "read", path = ".." }
]

[rpc_endpoints]
polygonAmoy = "${RPC_URL}"

[etherscan]
polygonAmoy = { key = "${ETHERSCAN_API_KEY}" }
